---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management-system
  template:
    metadata:
      labels:
        app: task-management-system
    spec:
      containers:
        - name: task-management-system
          image: vaishu160/task-management-system:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9301
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-root-credentials
                  key: password
