apiVersion: v1
kind: Service
metadata:
  name: mysql  # DNS name 
  labels:
    app: mysql
    tier: database
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001  # Ensure this port is available and doesn't conflict with other services
  selector:       # mysql Pod Should contain same labels
    app: mysql
    tier: database
